title: Nicholas Voris
#logo: /assets/img/headshot_circle.png
#description: [LinkedIN](https://www.linkedin.com/in/nicholas-voris/)
#show_downloads: true
theme: jekyll-theme-minimal
social:
  linkedin: https://www.linkedin.com/in/nicholas-voris/
