title: Nicholas Voris
#logo: /assets/img/headshot_circle.png
description:
linkedin: nicholas-voris
github: https://github.com/NicholasVoris/
email: nicholasgvoris@gmail.com
#show_downloads: true
theme: jekyll-theme-minimal
