title: Nicholas Voris
#logo: /assets/img/headshot_circle.png
description: [LinkedIN](https://www.kaggle.com/code/nickvoris/bellabeat-case-study/notebook)
#show_downloads: true
theme: jekyll-theme-minimal
