title: Nicholas Voris
#logo: /assets/img/headshot_circle.png
#description:
#show_downloads: true
theme: jekyll-theme-minimal

social:
  linkedin: www.linkedin.com/in/nicholas-voris
contact:
  email: nicholasgvoris@gmail.com
social:
  github: https://github.com/NicholasVoris
