title: Nicholas Voris
logo: /assets/Me.jpg
description: Data Analyst
linkedin: https://www.linkedin.com/in/nicholas-voris/
github: https://github.com/NicholasVoris/
email: nicholasgvoris@gmail.com
#show_downloads: true
theme: jekyll-theme-minimal
